# Generated by Django 5.2.12 on 2026-03-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.IntegerField(verbose_name='家賃_万円')),
                ('age', models.IntegerField(verbose_name='築年数_年')),
                ('distance', models.IntegerField(verbose_name='駅距離_km')),
                ('layout', models.IntegerField(verbose_name='専有面積_m²')),
            ],
        ),
    ]
